match op {
"vector3d_new" => op_vector3d_new(json_msg),
"distancia3d" => op_distancia3d(json_msg),
"normalizar_vector" => op_normalizar_vector(json_msg),
"producto_cruz" => op_producto_cruz(json_msg),
"producto_punto" => op_producto_punto(json_msg),
"suma_vector" => op_suma_vector(json_msg),
"resta_vector" => op_resta_vector(json_msg),
"magnitud_vector" => op_magnitud_vector(json_msg),
"vector_unitario" => op_vector_unitario(json_msg),
"proyeccion_vector" => op_proyeccion_vector(json_msg),
"angulo_vectores" => op_angulo_vectores(json_msg),
"plano3d" => op_plano3d(json_msg),
"matriz3x3" => op_matriz3x3(json_msg),
"rotacion_3d" => op_rotacion_3d(json_msg),
"rotacion_vector" => op_rotacion_vector(json_msg),
"recta3d" => op_recta3d(json_msg),
"interseccion_recta_plano" => op_interseccion_recta_plano(json_msg),
"interseccion_recta_recta" => op_interseccion_recta_recta(json_msg),
"trayectoria_lineal" => op_trayectoria_lineal(json_msg),
"trayectoria_circular" => op_trayectoria_circular(json_msg),
"offset_trayectoria" => op_offset_trayectoria(json_msg),
"trayectoria_helicoidal" => op_trayectoria_helicoidal(json_msg),
"trayectoria_spline" => op_trayectoria_spline(json_msg),
"interpolacion_velocidad" => op_interpolacion_velocidad(json_msg),
"simulacion_herramienta" => op_simulacion_herramienta(json_msg),
"generador_gcode" => op_generador_gcode(json_msg),
"setup_gcode" => op_setup_gcode(json_msg),
"selector_arcos" => selector_arcos(json_msg),
"selector_helicoidal" => selector_helicoidal(json_msg),

_ => Err("unknown op".into())
}
